QuantEcon/website

_posts/2019-11-04-anu-predoc.md
@jstac do we still want to use the `Early Career Researcher` language here?
=> [News] PreDoc Position for 2020 Post

_includes/quantecon-menubar.html, _layouts/default.html
Implementing the new menubar across QE sites.
=> Updated QuantEcon menubar

_posts/2020-04-07-python-lecture-split.md
Hi @jstac this is the news article about the new python lecture series split.
=> python lecture split news

_layouts/default.html
This replaces the HTML markup, css link and JS link for building the QE menu with simply a single js link which can be updated remotely.
=> QE Menubar injected via js

_posts/2020-05-14-data-science-student-project-showcase.md
Hi @jstac @jlperla here is the news post for the data science project showcase.
=> [Post] data-science-showcase

.github/workflows/build-and-deploy.yml, .github/workflows/preview.yml
This adds Github Action to:
1. build `jekyll` project
2. sync to aws s3 bucket: preview.quantecon.org (to test)
=> [Github Actions] add github action deploy workflows

pages/textbook.md
This PR adds a link to @jstac and @thomassargent30's preliminary draft of "High-Dimensional Probability" textbook.
=> Add link to Tom and John's (draft) textbook

pages/textbook.md
Applies minor updates to textbook page.
=> [UPD] update textbook page

_layouts/home.html, _projects/cheatsheets.md, _projects/julia.md, _projects/jupinx.md, _projects/lectures.md, _projects/notebooks.md, _projects/notes.md, _projects/python.md, _projects/textbook.md, _projects/workshops.md, pages/lectures.md
1) This PR is for an update to the homepage - a simplification
2) Update to the `/lectures/` page adding the 3 python and 1 continuous time markov chain lectures.
=> Homepage, lecture page updates

_posts/2021-09-08-julia-lectures-update.md
Updates links for julia news post
=> [NEWS] updates to links to new location

_posts/2022-04-12-sphinx-exercise
This is my best non-technical summary. Feel free to add anything I missed!
=> Add updates to sphinx exercise news

_posts/2022-05-12-random-surveys.md
@mmcky I accidentally merged this in but I reverted the commits
=> Add news items for random surveys lectures

pages/textbook.md
=> ENH: Update textbook page

_projects/lecture-jax
Adds a metadata file to show JAX on the project listing page.
=> Add Jax to the projects listing

_layouts/about.html
Adjust headings, remove animation and simplify layout.
=> Tidy team content on About page

_layouts/about.html, assets/main.scss
Adjust headings to be h1 through h4
=> Tidy team content

_layouts/team.html, assets/main.scss
- Changed page heading Team to h1
- Changed subsequent headings to nest
=> Fix heading hierarchy

pages/lectures.md
Add a redirect while #104 is worked out. 
@Aakash I will merge this to give this a go but let me know if a better way.
=> FIX: Add redirect for old lecture page

_layouts/home.html, _posts/2024-08-08-africa-workshop.md, _posts/2024-11-02-smit-google.md, _team-members/matthew.md, pages/about.md
This PR will collect update and changes to the QuantEcon organization website
**General Updates:**
addresses some of the items in #123
=> Updates to QuantEcon Website

_posts/2023-10-30-october-workshops.md, _posts/2024-05-15-cbc-workshop.md, _posts/2024-08-15-unimelb-workshop.md, pages/2024-11-20-rba-workshop.md, pages/workshops.md
This PR updates QuantEcon workshops page and associated news items.
=> Update workshops and news

_posts/2023-07-31-africa-workshop.md
=> FIX: fix image issue

_layouts/home.html, _posts/2024-11-22-rba-workshop.md
=> ENH: update feedback from jstac + news item

_lectures/lecture-datascience.md, _lectures/lecture-julia.md
This PR adds `Julia` and `data science` to the lecture page.
=> Add julia and datascience lecture series

_lectures/lecture-ctmc.md, _lectures/lecture-datascience.md, _lectures/lecture-julia.md
This PR adds in the CTMC lecture series
=> FIX: add in CTMC lectures

pages/analytics_dashboard.html
Update range of y-axis in monthly users plot.
cc @mmcky
=> Update range of y-axis in monthly users plot

_team-members/daisuke.md, _team-members/longye.md, _team-members/matthew.md, _team-members/richard.md, _team-members/smit.md, _team-members/zejin.md
Further updates to the team page
=> MAINT: updates to TEAM page
